execution_env=docker
#browser=Chrome
appUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
grid_url=http://localhost:4444/wd/hub
testDataFile=testData.xlsx
app.name=OpenCart
report.title=Automation Test Report
report.name=Functional Test Execution
report.theme=DARK
environment=QA

#################################################################################################################

# cd -> .jar folder -> run -- java -jar selenium-server-4.39.0.jar standalone in terminal / capture and copy grid URL
standalone_grid_url=http://192.168.0.106:4444/wd/hub 

################################################################################################################

dockerGrid_url=http://localhost:4444/wd/hub

################################################################################################################